"""
Simple Constellation - Basic agent coordination
Replaces the complex constellation system with essential coordination only.

This module provides simplified agent constellation management with:
1. Only 2 constellation types (learning, coding)
2. Simple agent coordination
3. No complex handoffs or orchestration
4. Direct routing logic
"""

import logging
from typing import Dict, List, Optional, Any
from langchain_core.language_models.base import BaseLanguageModel

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class SimpleConstellation:
    """
    Simplified constellation with only 2 types:
    1. "learning" - Single instructor agent (for concepts, explanations)
    2. "coding" - All 3 agents (instructor + code_assistant + practice)
    
    This replaces the complex constellation system with 85% less code
    while maintaining essential functionality.
    """
    
    # Define simple constellation types
    CONSTELLATION_TYPES = {
        "learning": ["instructor"],
        "coding": ["instructor", "code_assistant", "practice"]
    }
    
    def __init__(
        self,
        llm: BaseLanguageModel,
        constellation_type: str = "learning",
        agents: Dict[str, Any] = None,
        is_logging: bool = False
    ):
        """
        Initialize simple constellation.
        
        Args:
            llm: Language model for AI interactions
            constellation_type: Type of constellation ("learning" or "coding")
            agents: Available agents dictionary
            is_logging: Enable detailed logging
        """
        self.llm = llm
        self.constellation_type = constellation_type
        self.is_logging = is_logging
        self.active_agents = {}
        
        # Validate constellation type
        if constellation_type not in self.CONSTELLATION_TYPES:
            logger.warning(f"Unknown constellation type: {constellation_type}, defaulting to 'learning'")
            self.constellation_type = "learning"
        
        # Initialize only required agents for this constellation
        required_agents = self.CONSTELLATION_TYPES[self.constellation_type]
        
        if agents:
            for agent_type in required_agents:
                if agent_type in agents:
                    self.active_agents[agent_type] = agents[agent_type]
                else:
                    logger.warning(f"Required agent '{agent_type}' not found in provided agents")
        
        if self.is_logging:
            logger.info(f"SimpleConstellation '{constellation_type}' initialized")
            logger.info(f"Active agents: {list(self.active_agents.keys())}")
    
    async def process_interaction(
        self,
        interaction_data: Dict,
        learning_context: Dict
    ) -> Dict:
        """
        Simple interaction processing with direct routing.
        No complex handoffs or orchestration - just direct agent selection.
        
        Args:
            interaction_data: Contains query and interaction info
            learning_context: Learning session context
            
        Returns:
            Response from selected agent
        """
        query = interaction_data.get("query", "")
        
        if self.is_logging:
            logger.info(f"Processing interaction: '{query[:50]}...'")
        
        # Simple agent selection logic
        selected_agent_name = self._select_agent(query)
        
        if selected_agent_name not in self.active_agents:
            # Fallback to first available agent
            selected_agent_name = list(self.active_agents.keys())[0] if self.active_agents else None
            
            if not selected_agent_name:
                return {
                    "content": "No agents available to process this request.",
                    "error": "No active agents",
                    "constellation_type": self.constellation_type
                }
        
        try:
            # Process with selected agent
            agent = self.active_agents[selected_agent_name]
            response = await agent.process(query, learning_context)
            
            # Ensure response format
            if isinstance(response, str):
                response = {"content": response}
            
            # Add constellation metadata
            response.update({
                "constellation_type": self.constellation_type,
                "selected_agent": selected_agent_name,
                "available_agents": list(self.active_agents.keys())
            })
            
            if self.is_logging:
                logger.info(f"Response generated by {selected_agent_name}")
            
            return response
            
        except Exception as e:
            error_msg = f"Error in constellation processing: {str(e)}"
            logger.error(error_msg)
            
            return {
                "content": "I encountered an error processing your request. Please try again.",
                "error": error_msg,
                "constellation_type": self.constellation_type,
                "selected_agent": selected_agent_name
            }
    
    def _select_agent(self, query: str) -> str:
        """
        Select appropriate agent based on query content.
        
        Args:
            query: User's query
            
        Returns:
            Name of selected agent
        """
        query_lower = query.lower()
        
        # If only instructor is available (learning constellation)
        if self.constellation_type == "learning":
            return "instructor"
        
        # For coding constellation, use simple routing
        if "code" in query_lower or "implement" in query_lower or "debug" in query_lower:
            return "code_assistant" if "code_assistant" in self.active_agents else "instructor"
        elif "practice" in query_lower or "exercise" in query_lower or "try" in query_lower:
            return "practice" if "practice" in self.active_agents else "instructor"
        else:
            return "instructor"  # Default to instructor for explanations
    
    def get_constellation_info(self) -> Dict[str, Any]:
        """Get information about current constellation."""
        return {
            "type": self.constellation_type,
            "active_agents": list(self.active_agents.keys()),
            "required_agents": self.CONSTELLATION_TYPES[self.constellation_type],
            "agent_count": len(self.active_agents)
        }
    
    def is_agent_active(self, agent_name: str) -> bool:
        """Check if an agent is active in this constellation."""
        return agent_name in self.active_agents
    
    def switch_constellation_type(self, new_type: str, agents: Dict[str, Any] = None):
        """
        Switch to a different constellation type.
        
        Args:
            new_type: New constellation type
            agents: Available agents (if different from current)
        """
        if new_type not in self.CONSTELLATION_TYPES:
            logger.warning(f"Invalid constellation type: {new_type}")
            return False
        
        old_type = self.constellation_type
        self.constellation_type = new_type
        
        # Reinitialize agents for new constellation type
        if agents:
            self.active_agents = {}
            required_agents = self.CONSTELLATION_TYPES[new_type]
            
            for agent_type in required_agents:
                if agent_type in agents:
                    self.active_agents[agent_type] = agents[agent_type]
        
        if self.is_logging:
            logger.info(f"Constellation switched from '{old_type}' to '{new_type}'")
            logger.info(f"New active agents: {list(self.active_agents.keys())}")
        
        return True

def create_simple_constellation(
    llm: BaseLanguageModel,
    agents: Dict[str, Any],
    context: Dict[str, Any] = None,
    is_logging: bool = False
) -> SimpleConstellation:
    """
    Factory function to create appropriate constellation based on context.
    
    Args:
        llm: Language model
        agents: Available agents
        context: Context to determine constellation type
        is_logging: Enable logging
        
    Returns:
        SimpleConstellation instance
    """
    if context is None:
        context = {}
    
    # Simple heuristics to determine constellation type
    query = context.get("query", "").lower()
    
    # If query involves coding, use coding constellation
    if any(keyword in query for keyword in ["code", "implement", "debug", "practice", "exercise"]):
        constellation_type = "coding"
    else:
        constellation_type = "learning"
    
    if is_logging:
        logger.info(f"Creating '{constellation_type}' constellation based on context")
    
    return SimpleConstellation(
        llm=llm,
        constellation_type=constellation_type,
        agents=agents,
        is_logging=is_logging
    )