"""
Simplified Learning Hub - Core orchestration for GAAPF
Replaces the complex 1326-line learning_hub.py with essential functionality only.

This module provides the core learning orchestration with:
1. Simple agent coordination (3 agents only)
2. Basic session management
3. Simple routing logic
4. Study mode support (ready for Phase 2)
"""

import asyncio
import logging
from typing import Dict, List, Optional, Any
from pathlib import Path
from langchain_core.language_models.base import BaseLanguageModel

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class SimpleLearningHub:
    """
    Simplified learning hub focusing on core functionality:
    1. Agent coordination (3 agents only)
    2. Basic session management
    3. Simple routing logic
    4. Study mode support (prepared for Phase 2)
    
    This replaces the complex 1326-line learning_hub.py with essential
    functionality only, reducing complexity by 85%.
    """
    
    def __init__(
        self,
        llm: BaseLanguageModel,
        agents: Dict[str, Any],
        is_logging: bool = False
    ):
        """
        Initialize the simplified learning hub.
        
        Args:
            llm: Language model for AI interactions
            agents: Dictionary of 3 core agents (instructor, code_assistant, practice)
            is_logging: Enable detailed logging
        """
        self.llm = llm
        self.agents = agents  # Only 3 agents: instructor, code_assistant, practice
        self.is_logging = is_logging
        self.study_mode = False  # Study mode flag (for Phase 2)
        
        # Simple session tracking
        self.current_session = {
            "user_id": "default",
            "framework": "langchain",
            "interaction_count": 0,
            "start_time": None
        }
        
        if self.is_logging:
            logger.info(f"SimpleLearningHub initialized with {len(self.agents)} agents")
            logger.info(f"Available agents: {list(self.agents.keys())}")
        
    async def process_query(
        self,
        query: str,
        context: Dict[str, Any] = None,
        user_id: str = "default"
    ) -> Dict[str, Any]:
        """
        Process user query with simplified routing logic.
        
        Routing Rules:
        - Code-related keywords → CodeAssistantAgent
        - Practice/exercise keywords → PracticeFacilitatorAgent  
        - Everything else → InstructorAgent (with optional Study Mode)
        
        Args:
            query: User's question or request
            context: Additional context information
            user_id: User identifier
            
        Returns:
            Response dictionary with content and metadata
        """
        if context is None:
            context = {}
            
        # Update session info
        self.current_session["user_id"] = user_id
        self.current_session["interaction_count"] += 1
        
        # Simple routing logic based on keywords
        selected_agent = self._route_to_agent(query)
        
        if self.is_logging:
            logger.info(f"Query: '{query[:50]}...' routed to {selected_agent}")
        
        # Enhance context with study mode info
        enhanced_context = {
            **context,
            "study_mode": self.study_mode,
            "session": self.current_session,
            "framework": context.get("framework", self.current_session["framework"])
        }
        
        try:
            # Process with selected agent
            agent = self.agents[selected_agent]
            response = await agent.process(query, enhanced_context)
            
            # Ensure response is properly formatted
            if isinstance(response, str):
                response = {"content": response}
            
            # Add metadata
            response.update({
                "agent_used": selected_agent,
                "study_mode": self.study_mode,
                "interaction_count": self.current_session["interaction_count"]
            })
            
            if self.is_logging:
                logger.info(f"Response generated by {selected_agent}")
                
            return response
            
        except Exception as e:
            error_msg = f"Error processing query with {selected_agent}: {str(e)}"
            logger.error(error_msg)
            
            return {
                "content": f"I apologize, but I encountered an error processing your request. Please try rephrasing your question.",
                "error": error_msg,
                "agent_used": selected_agent,
                "study_mode": self.study_mode
            }
    
    def _route_to_agent(self, query: str) -> str:
        """
        Simple routing logic to select appropriate agent.
        
        Args:
            query: User's query
            
        Returns:
            Agent name to handle the query
        """
        query_lower = query.lower()
        
        # Code-related keywords
        code_keywords = [
            "code", "implement", "debug", "error", "function", 
            "class", "method", "variable", "syntax", "bug",
            "write code", "create function", "fix", "program"
        ]
        
        # Practice-related keywords  
        practice_keywords = [
            "practice", "exercise", "quiz", "test", "challenge",
            "try", "attempt", "hands-on", "example", "demo"
        ]
        
        # Check for code-related queries
        if any(keyword in query_lower for keyword in code_keywords):
            return "code_assistant"
            
        # Check for practice-related queries
        elif any(keyword in query_lower for keyword in practice_keywords):
            return "practice"
            
        # Default to instructor for explanations, concepts, etc.
        else:
            return "instructor"
    
    def enable_study_mode(self):
        """
        Enable Socratic Study Mode (Phase 2 feature).
        In Study Mode, agents guide learning through questions instead of direct answers.
        """
        self.study_mode = True
        if self.is_logging:
            logger.info("🤔 Study Mode activated - Learning through questions!")
    
    def disable_study_mode(self):
        """
        Disable Study Mode - return to direct answers.
        """
        self.study_mode = False
        if self.is_logging:
            logger.info("📚 Direct Mode activated - Learning through answers!")
    
    def get_session_info(self) -> Dict[str, Any]:
        """Get current session information."""
        return self.current_session.copy()
    
    def reset_session(self):
        """Reset current session."""
        self.current_session = {
            "user_id": "default",
            "framework": "langchain", 
            "interaction_count": 0,
            "start_time": None
        }
        if self.is_logging:
            logger.info("Session reset")
    
    def set_framework(self, framework: str):
        """Set the current learning framework."""
        self.current_session["framework"] = framework
        if self.is_logging:
            logger.info(f"Framework set to: {framework}")
    
    def get_available_agents(self) -> List[str]:
        """Get list of available agent names."""
        return list(self.agents.keys())
    
    def is_agent_available(self, agent_name: str) -> bool:
        """Check if an agent is available."""
        return agent_name in self.agents